version: "3"
services:

  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/mysite/assets/:ro
    ports:
      - "8000:80"
    depends_on: 
      - django

  django:
    build: ./web/
    restart: always
    command: >
      sh -c "python3 manage.py collectstatic --noinput 
      && uwsgi --ini mysite.uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/mysite/assets/


volumes:
  uwsgi_data:
  web_static:
